web:
  enable: true
  ip: 127.0.0.1
  port: 8080
  mode: debug
  readWriteTimeout: 60s
rpc:
  enable: true
  ip: 127.0.0.1
  port: 8088
log:
  level: debug
mysql:
  common:
    host: 127.0.0.1
    port: 3306
    username: root
    password:
    database: test
    logMode: true